COMP: Fix build against VTK > 9.1 adding missing "cmath" include
This commit fixes error like the following:

  /path/to/CIP/Common/vtkMultipleReconstructionKernelsPhaseCongruency.cxx:271:20:
  error: there are no arguments to ‘sqrt’ that depend on a template parameter, so a declaration of ‘sqrt’ must be available [-fpermissive]
    271 |               A += sqrt(meanf*meanf+((double) *inPtrs[idxK]) * ((double) *inPtrs[idxK]) );
        |                    ^~~~