COMP: Fix linking against ITK with custom namespace
This commit fixes regressions introduced in Slicer/Slicer@8f67453b0 (ENH: Add
support for importing "itk" from python wheels installed from PyPI).

It addresses link errors like the following by adding missing includes:

  CIP/Utilities/ITK/itkFactoryRegistration.cxx:11:38:
  error: ‘void slicer_itk::itkFactoryRegistration()’ should have been declared inside ‘slicer_itk’